### ISSUE TITLE
[Question] Is this compatible with Discord Chat Exporter?

### ISSUE THREAD

**Issue by GioRolf** [BorisNikulin/discord-chat-analysis#3]
Hi!
I wanted to ask if there is a way to use this project with a file exported with [DiscordChatExporter](https://github.com/Tyrrrz/DiscordChatExporter).
I think it would be really handy having some sort of compatibility.

Thank you for your work

**Comment by BorisNikulin** [comment]
Looking at [DiscordChatExporter's wiki](https://github.com/Tyrrrz/DiscordChatExporter/wiki/GUI%2C-CLI-and-Formats-explained#json-), I see that it supports outputting json. The Rmd uses the messages array as the data, as noted in #2.

You can modify the import line to account for this, similar to #2 as following:
```r
chat_json <- read_json('<json discord log>')$messages
```

This assumes the image for JSON output on the DiscordChatExporter wiki is accurate along with the Discord API message JSON object specification being the same as it was years ago (it should be).

**Comment by GioRolf** [comment]
Well, I'm confused, sorry... I'm not sure where to put my hands, I'm not that expert with python and R... I've edited the _'discord_chat_analysis.R '_ file, also following your last instructions.
But I have no idea how to run it... running the _'discord_chat_dl.py'_ file doesn't help, I suppose, since it's the downloader (am I right?)... Should I run it through an editor? I'm using Atom, at the momento
Sorry for the inaccuracy and incompetency D:

**Comment by BorisNikulin** [comment]
The *runnable* file is the Rmd (R markdown) which is R code + markdown. To run the code and convert the Rmd to markdown you use the R library rmarkdown. The makefile uses the library to generate markdown as following:
https://github.com/BorisNikulin/discord-chat-analysis/blob/dd89b3b41f06d6846933455e55165dc670c6441a/Makefile#L6-L7

So one of the easiest ways to create the *report* is to use the makefile as so
```
$ make README.md
```
which will create both a README.md and README.html (which requires pandoc).
The YAML front matter (the stuff at the top between ---'s) is what sets metadata and other parameters like the markdown language which pandoc uses to know to output the extra html file and what kind of markdown flavor it is.

The alternate more user friendly way is to use Rstudio which is an IDE for R that natively supports R markdown.

Due note that to render the Rmd you'll need to be able to run the R code which has a number of dependencies.
Off the top of my head you'll need to run in a R session
```r
install.packages("tidyverse") # meta package containing ggplot2, lubridate, purrr, etc
install.packages("data.table") # the dataframe lib used
install.packages("jsonlite")
install.packages("tidytext")
install.packages("igraph")
install.packages("ggraph") # requires a fortran compiler iirc, used for making the graph graphs at the end
```

Using Rstudio (or the nvimr plugin for vim) you can run the R chunks one at a time to see the graphs/output and make sure that section of the code works so you can incrementally install packages to get more the chunks to run as well as interactively add graphs or analysis similar to ipynb. You can also run а line at a time to validate the JSON is importing correctly as a list of [Discord message JSON objects](https://discord.com/developers/docs/resources/channel#message-object).

Also the .r file is more a an ad hoc script created as a prototype analysis which then was converted to the Rmd document.

Relevant links:
https://rmarkdown.rstudio.com/articles_intro.html
https://rmarkdown.rstudio.com/lesson-1.html
https://stackoverflow.com/questions/40563479/relationship-between-r-markdown-knitr-pandoc-and-bookdown

**Comment by BorisNikulin** [comment]
And yes, `discord_chat_dl.py` only downloads messages and saves it to disk.

**Comment by GioRolf** [comment]
Ok, thanks for the answer!
I've started running it through Rstudio, but it stops automatically at the "import data table" chunk. The error message is the following one
_Errore: Result 1 must be a single string, not NULL of length 0 Run `rlang::last_error()` to see where the error occurred.
11. stop(fallback)
10. signal_abort(cnd)
9. abort(message, x = x, expected = expected, actual = actual, what = what, arg = arg, ..., .subclass = c(.subclass, "purrr_error_bad_type"))
8. stop_bad_type(x, expected, actual = actual, what = what, arg = arg, recycle = recycle, message = message, .subclass = c(.subclass, "purrr_error_bad_vector"))
7. stop_bad_vector(x, expected_ptype, expected_length, what = what, arg = arg, index = index, ..., recycle = recycle, message = message, .subclass = c(.subclass, "purrr_error_bad_element_vector"))
6. purrr:::stop_bad_element_vector(NULL, 1, character(0), 1, what = "Result", arg = NULL, recycle = FALSE)
5. map_chr(chat_json, "timestamp")
4. eval(lhs, parent, parent)
3. eval(lhs, parent, parent)_
_2. map_chr(chat_json, "timestamp") %>% ymd_hms()_
_1. data.table(timestamp = map_chr(chat_json, "timestamp") %>% ymd_hms(), username = map_chr(chat_json, c("author", "username")) %>% as.factor(), message = map_chr(chat_json, "content"))_

And in the chat_tidying chunk, it says `Error in function_list[[i]](value) : object "username" not found`

At this point, I think that the output format of DiscordChatExporter is too different from the DiscordArchiver one...
Btw, how does the downloader work? Should I edit the field `def print_help(): print('Usage: {} [token] [channelId] [lastMessageId]'.format(sys.argv[0]))` replacing the placeholder with my data? Or there is another place where I should insert the token and the other data? And where is the output file saved? I can't make it work..

Thanks for your time, and sorry for the trouble

**Comment by BorisNikulin** [comment]
(Potential solution at the bottom)

The script uses command line arguments to receive input. As the help message points out, the program excepts a required token, channel id, and last message id, in that order, to work. So that would correspond to
```
$ python discord_chat_dl.py token123 1234 5678
```
Due note that the python script uses an potentially old and probably no longer working way of authentication so it may no longer work.

However, as long as the JSON is the same as defined by Discord, which is what DiscordChatExporter is receiving from Discord, I doubt DiscordChatExporter is messing with the schema except to maybe add top level meta data about how the logs where obtained/requested.

The error you're getting seems to be `purrr::map_chr` not liking that the input has no keys of `$timestamp`, `$author.username`, and `$content` and ends up with an empty list when extracting by those fields. This means the input list is not a list of [message JSON objects](https://discord.com/developers/docs/resources/channel#message-object) (represented as lists in R).

Since you are using Rstudio, the top right panel shows all objects defined in the R session as well as allowing you to drill into them to discover their structure (also available via the [str function](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/str)). The `chat_json` variable should be a list of the parsed JSON. It should be a list of [message objects](https://discord.com/developers/docs/resources/channel#message-object) and you can confirm that using the top right breakdown panel. The `chat` variable is then constructed by going through every message object and extracting the referenced fields such as `$timestamp`, `$author.username`, and `$content`. So you can check that the `chat_json` variable has those fields for each element in the list.

I suspect that the JSON you are importing has top level metadata attached and presume that the DiscordChatExporter JSON picture is accurate so the list of messages you want is actually buried 1 field in. Try
```r
chat_json <- read_json('<json discord log>')$messages
```
which will access the messages field in the JSON that I believe is the list of Discord message objects. Then when extracting the 3 fields, you should have a data table (data frame) with those three columns as the variable `chat`.

Also, I checked the message object schema and it seems to still contain the relevant fields. The only caveat was 
> The author object follows the structure of the user object, but is only a valid user in the case where the message is generated by a user or bot user. If the message is generated by a webhook, the author object corresponds to the webhook's id, username, and avatar. You can tell if a message is generated by a webhook by checking for the webhook_id on the message object.

So even if the author is a webhook the relevant fields are still present.

**Comment by GioRolf** [comment]
Thanks for the answer!
I'm sorry for the delay in my answer, I only found now the time to aswer to you!
I tried the new line of code, but it stops at the same row, with the same error. This time, running _rlang::last_trace()_ I get the following message:
```
<error/purrr_error_bad_element_vector>
Result 1 must be a single string, not NULL of length 0
Backtrace:
    x
 1. +-data.table::data.table(...)
 2. +-map_chr(chat_json, c("author", "username")) %>% as.factor()
 3. | \-base::eval(lhs, parent, parent)
 4. |   \-base::eval(lhs, parent, parent)
 5. +-purrr::map_chr(chat_json, c("author", "username"))
 6. \-purrr:::stop_bad_element_vector(...)
 7.   \-purrr:::stop_bad_vector(...)
 8.     \-purrr:::stop_bad_type(...)
```
Here is an extract from the chat_json file, I don't get where is the problem:

![Cattura](https://user-images.githubusercontent.com/31931819/98929964-39705400-24dc-11eb-886c-e9739803514f.JPG)

I'm sorry if the questions are trival
Thank you for your help!!

**Comment by BorisNikulin** [comment]
Looking at your parsed JSON, it seems the field called `username` ([author JSON spec here](https://discord.com/developers/docs/resources/user#user-object)) has been renamed to `name`.

Try
```r
chat <- data.table(
	timestamp = map_chr(chat_json, 'timestamp') %>% ymd_hms(),
	username = map_chr(chat_json, c('author', 'name')) %>% as.factor(),
	message = map_chr(chat_json, 'content')
	)
```
that is extract `$author.name` instead of `$author.username` into the `username` column of `chat`.

**Comment by BorisNikulin** [comment]
More or less the above will work. See
https://github.com/BorisNikulin/discord-chat-analysis/blob/a31cbbbafc5365af6a4b8cbb7f2b713487013eaa/README.Rmd#L28-L43
https://github.com/BorisNikulin/discord-chat-analysis/blob/a31cbbbafc5365af6a4b8cbb7f2b713487013eaa/README.Rmd#L55-L73
which does work with DiscordChatExporter JSON logs.

Due note that 
https://github.com/BorisNikulin/discord-chat-analysis/blob/4257c571c643f306d0d35f487204c85e97b9a243/README.Rmd#L64-L77
can filter out all your messages causing later parts to break. In particular adjust the `N < 100` to adjust how many messages a user must have to not be filtered out.

**Comment by BorisNikulin** [comment]
#7 is merged into master and handles DiscordChatExporter by default. Due note about the over filtering that may happened as noted above.
